name: Node.js Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18.17.1
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.1'

    - run: npm ci
    - run: npm run build
      # This step will fail if `npm run build` fails, blocking the merge
